name: test
on:
  workflow_dispatch:
    inputs:
      inputOne:
        required: true
        type: string
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: echo "wwwww"
