name: test
on:
  workflow_dispatch:
    inputs:
      inputOne:
        required: true
        type: string
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "wwwww"
